# Generated by Django 5.2.4 on 2025-07-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
